version: '2'
services:
  mongo:
    image: mongo

  board:
    build: .
    image: board
    ports:
      - "3000:3000"
    command: npm start
    working_dir: /usr/board
    environment:
      - PORT=3000
      - MONGO_URI=mongo
    links:
      - mongo
    depends_on:
      - mongo
